[v1]
"cargo-outdated 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-outdated.exe"]
"racer 1.2.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer.exe"]
"rustfmt 0.6.2 (registry+file:///usr/local/share/cargo)" = ["cargo-fmt.exe", "rustfmt.exe"]
"treesize 0.2.1 (git+https://github.com/melak47/treesize-rs#742aebb3e66bd14421eb148e7f7981d50c6d1423)" = ["treesize.exe"]
